package com.questy.admin;

import com.questy.dao.FlowRuleDao;
import com.questy.dao.QuestionDao;
import com.questy.dao.QuestionOptionDao;
import com.questy.domain.Question;
import com.questy.domain.QuestionOption;
import com.questy.enums.AnswerVisibilityEnum;
import com.questy.services.FlowRuleServices;
import com.questy.services.QuestionOptionServices;
import com.questy.services.QuestionServices;
import com.questy.utils.DatabaseUtils;

import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;

public class Basic {

    public static void create(Integer networkId) throws Exception {

        Integer userId = 2;

        Integer addedQuestionRef = null;
        Question addedQuestion = null;
        QuestionOption option = null;
        Map<String, Question> questions = new HashMap<String, Question>();

        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "What is your gender?", 0, 1, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                {
                    "Male",
                    "Female"
                });
            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), QuestionDao.ROOT_QUESTION_REF, QuestionOptionDao.ANY_OPTION_REF, addedQuestion.getRef());


            // Adding question to list
            questions.put("gender", addedQuestion);
        }

        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "In what country were you born?", 0, 1, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                {
                    "Afghanistan               ",
                    "Albania                   ",
                    "Algeria                   ",
                    "Andorra                   ",
                    "Angola                    ",
                    "Antigua and Barbuda       ",
                    "Argentina                 ",
                    "Armenia                   ",
                    "Australia                 ",
                    "Austria                   ",
                    "Azerbaijan                ",
                    "Bahamas, The              ",
                    "Bahrain                   ",
                    "Bangladesh                ",
                    "Barbados                  ",
                    "Belarus                   ",
                    "Belgium                   ",
                    "Belize                    ",
                    "Benin                     ",
                    "Bhutan                    ",
                    "Bolivia                   ",
                    "Bosnia and Herzegovina    ",
                    "Botswana                  ",
                    "Brazil                    ",
                    "Britain                   ",
                    "Brunei                    ",
                    "Bulgaria                  ",
                    "Burkina Faso              ",
                    "Burundi                   ",
                    "(Burma)                   ",
                    "Cambodia                  ",
                    "Cameroon                  ",
                    "Canada                    ",
                    "Cape Verde                ",
                    "Central African Republic  ",
                    "Chad                      ",
                    "Chile                     ",
                    "China                     ",
                    "Colombia                  ",
                    "Comoros                   ",
                    "Congo                     ",
                    "Costa Rica                ",
                    "Cote D'Ivoire             ",
                    "Croatia                   ",
                    "Cuba                      ",
                    "Cyprus                    ",
                    "Czech Republic            ",
                    "Czechoslovakia            ",
                    "Denmark                   ",
                    "Djibouti                  ",
                    "Dominica                  ",
                    "Dominican Republic        ",
                    "Ecuador                   ",
                    "Egypt                     ",
                    "El Salvador               ",
                    "England                   ",
                    "Equatorial Guinea         ",
                    "Eritrea                   ",
                    "Estonia                   ",
                    "Ethiopia                  ",
                    "Fiji                      ",
                    "Finland                   ",
                    "France                    ",
                    "Gabon                     ",
                    "Gambia, The               ",
                    "Georgia                   ",
                    "Germany                   ",
                    "Ghana                     ",
                    "Great Britain             ",
                    "Greece                    ",
                    "Greenland                 ",
                    "Grenada                   ",
                    "Guatemala                 ",
                    "Guinea                    ",
                    "Guinea-Bissau             ",
                    "Guyana                    ",
                    "Haiti                     ",
                    "Honduras                  ",
                    "Hungary                   ",
                    "Iceland                   ",
                    "India                     ",
                    "Indonesia                 ",
                    "Iran                      ",
                    "Iraq                      ",
                    "Ireland                   ",
                    "Ireland, Northern         ",
                    "Israel                    ",
                    "Italy                     ",
                    "Jamaica                   ",
                    "Japan                     ",
                    "Java                      ",
                    "Jordan                    ",
                    "Kazakhstan                ",
                    "Kenya                     ",
                    "Kiribati                  ",
                    "Korea, North              ",
                    "Korea, South              ",
                    "Kuwait                    ",
                    "Kyrgyzstan                ",
                    "Laos                      ",
                    "Latvia                    ",
                    "Lebanon                   ",
                    "Lesotho                   ",
                    "Liberia                   ",
                    "Libya                     ",
                    "Liechtenstein             ",
                    "Lithuania                 ",
                    "Luxembourg                ",
                    "Macedonia                 ",
                    "Madagascar                ",
                    "Malawi                    ",
                    "Malaysia                  ",
                    "Maldives                  ",
                    "Mali                      ",
                    "Malta                     ",
                    "Marshall Islands          ",
                    "Mauritania                ",
                    "Mauritius                 ",
                    "Mexico                    ",
                    "Micronesia                ",
                    "Moldova                   ",
                    "Monaco                    ",
                    "Mongolia                  ",
                    "Morocco                   ",
                    "Mozambique                ",
                    "Myanmar (Burma)           ",
                    "Namibia                   ",
                    "Nauru                     ",
                    "Nepal                     ",
                    "Netherlands, The          ",
                    "New Zealand               ",
                    "Nicaragua                 ",
                    "Niger                     ",
                    "Nigeria                   ",
                    "North Korea               ",
                    "Norway                    ",
                    "Northern Ireland          ",
                    "Oman                      ",
                    "Pakistan                  ",
                    "Palau                     ",
                    "Panama                    ",
                    "Papua New Guinea          ",
                    "Paraguay                  ",
                    "Peru                      ",
                    "Philippines, The          ",
                    "Poland                    ",
                    "Portugal                  ",
                    "Qatar                     ",
                    "Romania                   ",
                    "Russia                    ",
                    "Rwanda                    ",
                    "St. Kitts and Nevis       ",
                    "St. Lucia                 ",
                    "St. Vincent               ",
                    "Samoa                     ",
                    "San Marino                ",
                    "Sao Tome and Principe     ",
                    "Saudi Arabia              ",
                    "Scotland                  ",
                    "Senegal                   ",
                    "Seychelles                ",
                    "Sierra Leone              ",
                    "Singapore                 ",
                    "Slovakia                  ",
                    "Slovenia                  ",
                    "Solomon Islands           ",
                    "Somalia                   ",
                    "South Africa              ",
                    "South Korea               ",
                    "Spain                     ",
                    "Sri Lanka                 ",
                    "Sudan                     ",
                    "Suriname                  ",
                    "Swaziland                 ",
                    "Sweden                    ",
                    "Switzerland               ",
                    "Syria                     ",
                    "Taiwan                    ",
                    "Tajikistan                ",
                    "Tanzania                  ",
                    "Thailand                  ",
                    "Togo                      ",
                    "Tonga                     ",
                    "Trinidad and Tobago       ",
                    "Tunisia                   ",
                    "Turkey                    ",
                    "Turkmenistan              ",
                    "Tuvalu                    ",
                    "Uganda                    ",
                    "Ukraine                   ",
                    "United Arab Emirates      ",
                    "United Kingdom            ",
                    "United States             ",
                    "Uruguay                   ",
                    "Uzbekistan                ",
                    "Vanuatu                   ",
                    "Vatican City              ",
                    "Venezuela                 ",
                    "Vietnam                   ",
                    "Wales                     ",
                    "Yemen                     ",
                    "Yugoslavia                ",
                    "Zambia                    ",
                    "Zimbabwe                  "
                });
            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), QuestionDao.ROOT_QUESTION_REF, QuestionOptionDao.ANY_OPTION_REF, addedQuestion.getRef());

            // Adding question to list
            questions.put("born", addedQuestion);
        }

        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "Select all the countries have you lived in?", 0, 5, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                {
                    "Afghanistan               ",
                    "Albania                   ",
                    "Algeria                   ",
                    "Andorra                   ",
                    "Angola                    ",
                    "Antigua and Barbuda       ",
                    "Argentina                 ",
                    "Armenia                   ",
                    "Australia                 ",
                    "Austria                   ",
                    "Azerbaijan                ",
                    "Bahamas, The              ",
                    "Bahrain                   ",
                    "Bangladesh                ",
                    "Barbados                  ",
                    "Belarus                   ",
                    "Belgium                   ",
                    "Belize                    ",
                    "Benin                     ",
                    "Bhutan                    ",
                    "Bolivia                   ",
                    "Bosnia and Herzegovina    ",
                    "Botswana                  ",
                    "Brazil                    ",
                    "Britain                   ",
                    "Brunei                    ",
                    "Bulgaria                  ",
                    "Burkina Faso              ",
                    "Burundi                   ",
                    "(Burma)                   ",
                    "Cambodia                  ",
                    "Cameroon                  ",
                    "Canada                    ",
                    "Cape Verde                ",
                    "Central African Republic  ",
                    "Chad                      ",
                    "Chile                     ",
                    "China                     ",
                    "Colombia                  ",
                    "Comoros                   ",
                    "Congo                     ",
                    "Costa Rica                ",
                    "Cote D'Ivoire             ",
                    "Croatia                   ",
                    "Cuba                      ",
                    "Cyprus                    ",
                    "Czech Republic            ",
                    "Czechoslovakia            ",
                    "Denmark                   ",
                    "Djibouti                  ",
                    "Dominica                  ",
                    "Dominican Republic        ",
                    "Ecuador                   ",
                    "Egypt                     ",
                    "El Salvador               ",
                    "England                   ",
                    "Equatorial Guinea         ",
                    "Eritrea                   ",
                    "Estonia                   ",
                    "Ethiopia                  ",
                    "Fiji                      ",
                    "Finland                   ",
                    "France                    ",
                    "Gabon                     ",
                    "Gambia, The               ",
                    "Georgia                   ",
                    "Germany                   ",
                    "Ghana                     ",
                    "Great Britain             ",
                    "Greece                    ",
                    "Greenland                 ",
                    "Grenada                   ",
                    "Guatemala                 ",
                    "Guinea                    ",
                    "Guinea-Bissau             ",
                    "Guyana                    ",
                    "Haiti                     ",
                    "Honduras                  ",
                    "Hungary                   ",
                    "Iceland                   ",
                    "India                     ",
                    "Indonesia                 ",
                    "Iran                      ",
                    "Iraq                      ",
                    "Ireland                   ",
                    "Ireland, Northern         ",
                    "Israel                    ",
                    "Italy                     ",
                    "Jamaica                   ",
                    "Japan                     ",
                    "Java                      ",
                    "Jordan                    ",
                    "Kazakhstan                ",
                    "Kenya                     ",
                    "Kiribati                  ",
                    "Korea, North              ",
                    "Korea, South              ",
                    "Kuwait                    ",
                    "Kyrgyzstan                ",
                    "Laos                      ",
                    "Latvia                    ",
                    "Lebanon                   ",
                    "Lesotho                   ",
                    "Liberia                   ",
                    "Libya                     ",
                    "Liechtenstein             ",
                    "Lithuania                 ",
                    "Luxembourg                ",
                    "Macedonia                 ",
                    "Madagascar                ",
                    "Malawi                    ",
                    "Malaysia                  ",
                    "Maldives                  ",
                    "Mali                      ",
                    "Malta                     ",
                    "Marshall Islands          ",
                    "Mauritania                ",
                    "Mauritius                 ",
                    "Mexico                    ",
                    "Micronesia                ",
                    "Moldova                   ",
                    "Monaco                    ",
                    "Mongolia                  ",
                    "Morocco                   ",
                    "Mozambique                ",
                    "Myanmar (Burma)           ",
                    "Namibia                   ",
                    "Nauru                     ",
                    "Nepal                     ",
                    "Netherlands, The          ",
                    "New Zealand               ",
                    "Nicaragua                 ",
                    "Niger                     ",
                    "Nigeria                   ",
                    "North Korea               ",
                    "Norway                    ",
                    "Northern Ireland          ",
                    "Oman                      ",
                    "Pakistan                  ",
                    "Palau                     ",
                    "Panama                    ",
                    "Papua New Guinea          ",
                    "Paraguay                  ",
                    "Peru                      ",
                    "Philippines, The          ",
                    "Poland                    ",
                    "Portugal                  ",
                    "Qatar                     ",
                    "Romania                   ",
                    "Russia                    ",
                    "Rwanda                    ",
                    "St. Kitts and Nevis       ",
                    "St. Lucia                 ",
                    "St. Vincent               ",
                    "Samoa                     ",
                    "San Marino                ",
                    "Sao Tome and Principe     ",
                    "Saudi Arabia              ",
                    "Scotland                  ",
                    "Senegal                   ",
                    "Seychelles                ",
                    "Sierra Leone              ",
                    "Singapore                 ",
                    "Slovakia                  ",
                    "Slovenia                  ",
                    "Solomon Islands           ",
                    "Somalia                   ",
                    "South Africa              ",
                    "South Korea               ",
                    "Spain                     ",
                    "Sri Lanka                 ",
                    "Sudan                     ",
                    "Suriname                  ",
                    "Swaziland                 ",
                    "Sweden                    ",
                    "Switzerland               ",
                    "Syria                     ",
                    "Taiwan                    ",
                    "Tajikistan                ",
                    "Tanzania                  ",
                    "Thailand                  ",
                    "Togo                      ",
                    "Tonga                     ",
                    "Trinidad and Tobago       ",
                    "Tunisia                   ",
                    "Turkey                    ",
                    "Turkmenistan              ",
                    "Tuvalu                    ",
                    "Uganda                    ",
                    "Ukraine                   ",
                    "United Arab Emirates      ",
                    "United Kingdom            ",
                    "United States             ",
                    "Uruguay                   ",
                    "Uzbekistan                ",
                    "Vanuatu                   ",
                    "Vatican City              ",
                    "Venezuela                 ",
                    "Vietnam                   ",
                    "Wales                     ",
                    "Yemen                     ",
                    "Yugoslavia                ",
                    "Zambia                    ",
                    "Zimbabwe                  "
                });
            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), QuestionDao.ROOT_QUESTION_REF, QuestionOptionDao.ANY_OPTION_REF, addedQuestion.getRef());

            // Adding question to list
            questions.put("lived", addedQuestion);
        }


        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "What year were you born?", 0, 1, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                {
                    "2012",
                    "2011",
                    "2010",
                    "2009",
                    "2008",
                    "2007",
                    "2006",
                    "2005",
                    "2004",
                    "2003",
                    "2002",
                    "2001",
                    "2000",
                    "1999",
                    "1998",
                    "1997",
                    "1996",
                    "1995",
                    "1994",
                    "1993",
                    "1992",
                    "1991",
                    "1990",
                    "1989",
                    "1988",
                    "1987",
                    "1986",
                    "1985",
                    "1984",
                    "1983",
                    "1982",
                    "1981",
                    "1980",
                    "1979",
                    "1978",
                    "1977",
                    "1976",
                    "1975",
                    "1974",
                    "1973",
                    "1972",
                    "1971",
                    "1970",
                    "1969",
                    "1968",
                    "1967",
                    "1966",
                    "1965",
                    "1964",
                    "1963",
                    "1962",
                    "1961",
                    "1960",
                    "1959",
                    "1958",
                    "1957",
                    "1956",
                    "1955",
                    "1954",
                    "1953",
                    "1952",
                    "1951",
                    "1950",
                    "1949",
                    "1948",
                    "1947",
                    "1946",
                    "1945",
                    "1944",
                    "1943",
                    "1942",
                    "1941",
                    "1940",
                    "1939",
                    "1938",
                    "1937",
                    "1936",
                    "1935",
                    "1934",
                    "1933",
                    "1932",
                    "1931",
                    "1930",
                    "1929",
                    "1928",
                    "1927",
                    "1926",
                    "1925",
                    "1924",
                    "1923",
                    "1922",
                    "1921",
                    "1920",
                    "1919",
                    "1918",
                    "1917",
                    "1916",
                    "1915",
                    "1914",
                    "1913",
                    "1912",
                    "1911",
                    "1910",
                    "1909",
                    "1908",
                });
            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), QuestionDao.ROOT_QUESTION_REF, QuestionOptionDao.ANY_OPTION_REF, addedQuestion.getRef());

            // Adding question to list
            questions.put("year", addedQuestion);
        }


        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "Which activities do you enjoy doing or going to?", 0, 5, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                    {
                        "Sports / Outdoor",
                        "Video games",
                        "Board or Card games",
                        "Dancing",
                        "Cooking",
                        "Playing music",
                        "Drawing",
                        "Shopping",
                        "Concerts",
                        "Exploring a city",
                    });
            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), QuestionDao.ROOT_QUESTION_REF, QuestionOptionDao.ANY_OPTION_REF, addedQuestion.getRef());

            // Adding question to list
            questions.put("activities", addedQuestion);


            {
                // Adding question
                addedQuestionRef = QuestionServices.insert(userId, networkId, "Which sports or outdoor activities do you like doing?", 0, 10, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

                // Adding options
                addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
                QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                    {
                        "Adventure Racing          ",
                        "Aerobatics                ",
                        "Aerobics                  ",
                        "Aeromodelling             ",
                        "Aikido                    ",
                        "Air Sports                ",
                        "Airsoft                   ",
                        "Archery                   ",
                        "Arm Wrestling             ",
                        "Astronautics              ",
                        "Athletics                 ",
                        "Australian Football       ",
                        "Auto Racing               ",
                        "Backgammon                ",
                        "Backpacking               ",
                        "Badminton                 ",
                        "Ballooning                ",
                        "Bandy                     ",
                        "Baseball                  ",
                        "Basketball                ",
                        "Battledore                ",
                        "Beach Volleyball          ",
                        "Biathlon                  ",
                        "Bicycle Polo              ",
                        "Bicycling                 ",
                        "Billiards                 ",
                        "Bird Watching             ",
                        "BMX Stunt Bike            ",
                        "Boating                   ",
                        "Boball                    ",
                        "Bobsledding               ",
                        "Bocce                     ",
                        "Bodyboarding              ",
                        "Bodybuilding              ",
                        "Boomerang                 ",
                        "Boules                    ",
                        "Bowling                   ",
                        "Boxing                    ",
                        "Bridge                    ",
                        "Broomball                 ",
                        "Bull Fighting             ",
                        "Bungee Jumping            ",
                        "Buzkashi                  ",
                        "Caber Toss                ",
                        "Camel Riding              ",
                        "Camogie                   ",
                        "Camping                   ",
                        "Canoeing                  ",
                        "Canopying                 ",
                        "Cave Diving               ",
                        "Cave Exploration          ",
                        "Cheerleading              ",
                        "Chess                     ",
                        "Climbing                  ",
                        "Cock Fighting             ",
                        "Cricket                   ",
                        "Croquet                   ",
                        "Curling                   ",
                        "Cycling                   ",
                        "Dance                     ",
                        "Darts                     ",
                        "Discus Throwing           ",
                        "Diving                    ",
                        "Dodge Ball                ",
                        "Dog Sledding              ",
                        "Dragon Boating            ",
                        "Double Dutch              ",
                        "Elephant Polo             ",
                        "Elephant Riding           ",
                        "Falconry                  ",
                        "Feather Bowling           ",
                        "Fencing                   ",
                        "Field Hockey              ",
                        "Fin Swimming              ",
                        "Fishing                   ",
                        "Five Pin Bowling          ",
                        "Floor Hockey              ",
                        "Floorball                 ",
                        "Football                  ",
                        "Foot Bag                  ",
                        "Football                  ",
                        "Fox Hunting               ",
                        "Free Diving               ",
                        "Frisbee                   ",
                        "Front Tennis              ",
                        "Futsal                    ",
                        "Gaelic Football           ",
                        "Gambling                  ",
                        "Geocaching                ",
                        "Goal Ball                 ",
                        "Go Karting                ",
                        "Golf                      ",
                        "Gridiron Football         ",
                        "Greyhound Racing          ",
                        "Gymnastics                ",
                        "Hammer Throw              ",
                        "Handball                  ",
                        "Hang Gliding              ",
                        "Hardball Hockey           ",
                        "Harpastum                 ",
                        "High Fives Netball        ",
                        "High Jump                 ",
                        "Hiking                    ",
                        "Hockey Bocky              ",
                        "Homing Pigeons            ",
                        "Hopscotch                 ",
                        "Horse Polo                ",
                        "Horse Racing              ",
                        "Horseback Riding          ",
                        "Horseback Hurdle Jumping  ",
                        "Horseshoe Pitching        ",
                        "Hula Hooping              ",
                        "Hunting                   ",
                        "Hurdle Jumpingsf          ",
                        "Hurdles                   ",
                        "Hurling                   ",
                        "Ice Boating               ",
                        "Ice Figure Skating        ",
                        "Ice Fishing               ",
                        "Ice Hockey                ",
                        "Ice Sailing               ",
                        "Ice Skating               ",
                        "Ice Speed Skating         ",
                        "Indoor Rowing             ",
                        "Inline Hockey             ",
                        "Inline Skating            ",
                        "Inline Speed Skating      ",
                        "Innebandy (Floorball)     ",
                        "Jai Alai                  ",
                        "Javelin Toss              ",
                        "Jet Skiing                ",
                        "Jogging                   ",
                        "Jujitsu (Ju Jitsu)        ",
                        "Judo                      ",
                        "Kabaddi                   ",
                        "Karate                    ",
                        "Kayaking                  ",
                        "Kendo                     ",
                        "Kick Ball                 ",
                        "Kick Boxing               ",
                        "Kite Flying               ",
                        "Kite Surfing              ",
                        "Knife Throwing            ",
                        "Korfball                  ",
                        "Kubb                      ",
                        "Kung Fu                   ",
                        "Lacrosse                  ",
                        "Land Sailing              ",
                        "Laser Games               ",
                        "Lawn Bowling              ",
                        "Lawn Tennis               ",
                        "Lawnmower Racing          ",
                        "Long Jump                 ",
                        "Luge                      ",
                        "Lumberjack Games          ",
                        "Marbles                   ",
                        "Martial Arts              ",
                        "Metal Detecting           ",
                        "Miniature Golf            ",
                        "Monoskiing                ",
                        "Motocross                 ",
                        "Motorcycle Racing         ",
                        "Mountain Biking           ",
                        "Mountaineering            ",
                        "Navigation                ",
                        "Netball                   ",
                        "Off Road Skating          ",
                        "Off Road Vehicles         ",
                        "Orienteering              ",
                        "Outdoor Rowing            ",
                        "Paddleball                ",
                        "Paddling                  ",
                        "Paintball                 ",
                        "Pentathlon                ",
                        "Personal Watercraft       ",
                        "Pentanque                 ",
                        "Pigeon Racing             ",
                        "Pilates                   ",
                        "Ping Pong (Table Tennis)  ",
                        "Platform Tennis           ",
                        "Pogo Stick Jumping        ",
                        "Polar Exploration         ",
                        "Pole Vaulting             ",
                        "Polo                      ",
                        "Power Boating             ",
                        "Powerlifting              ",
                        "Pro Wrestling             ",
                        "Push Scooters             ",
                        "Quad Roller Skating       ",
                        "Quad Speed Skating        ",
                        "Quik Cricket              ",
                        "Quoits                    ",
                        "Racquetball               ",
                        "Rafting                   ",
                        "Rink Hockey               ",
                        "Rock Climbing             ",
                        "Rodeo                     ",
                        "Rogaining                 ",
                        "Rolle Bolle               ",
                        "Roller Basketball         ",
                        "Roller Derby              ",
                        "Roller Figure Skating     ",
                        "Roller Hockey             ",
                        "Rollerblading             ",
                        "Rollerjoring              ",
                        "Rollerskiing              ",
                        "Roller Soccer             ",
                        "Roping                    ",
                        "Rounders                  ",
                        "Rowing, Indoor            ",
                        "Rowing, Outdoor           ",
                        "Rugby                     ",
                        "Rugby League              ",
                        "Rugby Sevens              ",
                        "Rugby Union               ",
                        "Running                   ",
                        "Sailing                   ",
                        "Salibandy                 ",
                        "Scooter Riding            ",
                        "Scuba Diving              ",
                        "Sepak Takraw              ",
                        "Sheep Herding             ",
                        "Shinty                    ",
                        "Shooting                  ",
                        "Shot Put                  ",
                        "Shuffleboard              ",
                        "Skate Sailing             ",
                        "Skateboarding             ",
                        "Skating                   ",
                        "Skeet Shooting            ",
                        "Ski Boarding              ",
                        "Skiing                    ",
                        "Skijoring                 ",
                        "Skipping Rope             ",
                        "Skydiving                 ",
                        "Sledding                  ",
                        "Snooker                   ",
                        "Snow Biking               ",
                        "Snow Kiting               ",
                        "Snow Skating              ",
                        "Snowboarding              ",
                        "Snowmobiling              ",
                        "Snowshoeing               ",
                        "Soccer                    ",
                        "Softball                  ",
                        "Spearfishing              ",
                        "Speleology                ",
                        "Squash                    ",
                        "Squirrel Fishing          ",
                        "Steeplechase              ",
                        "Stone Put                 ",
                        "Street Hockey             ",
                        "Street Luge               ",
                        "Sumo Wrestling            ",
                        "Surfing                   ",
                        "Swimming                  ",
                        "Synchronized Skating      ",
                        "Synchronized Swimming     ",
                        "Table Soccer (Foosball)   ",
                        "Table Tennis              ",
                        "Taekwondo                 ",
                        "Tai Chi                   ",
                        "Target Shooting           ",
                        "Tchoukball                ",
                        "Team Handball             ",
                        "Ten Pin Bowling           ",
                        "Tennis                    ",
                        "Tetherball                ",
                        "Three Pin Bowling         ",
                        "Tobogganing               ",
                        "Torball                   ",
                        "Track and Field           ",
                        "Track Hurdle Jumping      ",
                        "Tractor Pull              ",
                        "Trampoline                ",
                        "Triathlon                 ",
                        "Trigon                    ",
                        "Tug of War                ",
                        "Turtle Racing             ",
                        "Ultimate Frisbee          ",
                        "Underwater Hockey         ",
                        "Underwater Rugby          ",
                        "Unicycling                ",
                        "Unihockey (Floorball)     ",
                        "Varpa                     ",
                        "Volleyball                ",
                        "Wakeboarding              ",
                        "Walking                   ",
                        "Water Aerobics            ",
                        "Water Ballet              ",
                        "Water Basketball          ",
                        "Water Polo                ",
                        "Waterskiing               ",
                        "Weight Training           ",
                        "Weightlifting             ",
                        "Whitewater Rafting        ",
                        "Windsurfing               ",
                        "Winter Triathlon          ",
                        "Wrestling                 ",
                        "Yoga                      ",
                        "YoYo                      ",
                        "Ziplining                 "
                    });

                addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

                // Adding flow rules
                option = questions.get("activities").findOptionByText("Sports / Outdoor");
                FlowRuleServices.insert(addedQuestion.getNetworkId(), option.getQuestionRef(), option.getRef(), addedQuestion.getRef());

                // Adding question to list
                questions.put("sports", addedQuestion);
            }

            {
                // Adding question
                addedQuestionRef = QuestionServices.insert(userId, networkId, "Which video game console do you prefer when playing video games?", 0, 10, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

                // Adding options
                addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
                QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                    {
                        "Apple iOS                ",
                        "Mcrosoft Xbox Kinect     ",
                        "Microsoft Xbox           ",
                        "Nintendo 64              ",
                        "Nintendo 64DD            ",
                        "Sega Genesis             ",
                        "Sony PlayStation         ",
                        "Sony PlayStation 2       ",
                        "Sony PlayStation 3       ",
                        "Sony PlayStation Move    ",
                        "Super Nintendo           ",
                    });

                addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

                // Adding flow rules
                option = questions.get("activities").findOptionByText("Video games");
                FlowRuleServices.insert(addedQuestion.getNetworkId(), option.getQuestionRef(), option.getRef(), addedQuestion.getRef());


                // Adding question to list
                questions.put("video-games", addedQuestion);
            }

            {
                // Adding question
                addedQuestionRef = QuestionServices.insert(userId, networkId, "Which board or card games do you like to play?", 0, 10, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, true);

                // Adding options
                addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
                QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                    {
                        "18XX                                       ",
                        "(This Game Is) Bonkers!                    ",
                        "1313 Dead End Drive                        ",
                        "221B Baker Street                          ",
                        "30 Seconds                                 ",
                        "Abalone                                    ",
                        "About Time                                 ",
                        "Acquire                                    ",
                        "Acronymble                                 ",
                        "Adel Verpflichtet                          ",
                        "Afrikan tähti                              ",
                        "Agon                                       ",
                        "Agricola                                   ",
                        "Air Charter                                ",
                        "Aladdin's Dragons                          ",
                        "Alhambra                                   ",
                        "Alias                                      ",
                        "American Megafauna                         ",
                        "Amun-Re                                    ",
                        "Anti-Monopoly                              ",
                        "Apples to Apples                           ",
                        "Articulate!                                ",
                        "Attack!                                    ",
                        "Auf Achse                                  ",
                        "Australia                                  ",
                        "Axis & Allies                              ",
                        "Backgammon                                 ",
                        "Balderdash                                 ",
                        "Bananagrams                                ",
                        "Bang!                                      ",
                        "Barbarossa                                 ",
                        "Battleship                                 ",
                        "Beer pong                                  ",
                        "Bezzerwizzer                               ",
                        "Blankety Blank                             ",
                        "Blockhead!                                 ",
                        "Blokus                                     ",
                        "Blood Bowl                                 ",
                        "Blood Feud in New York                     ",
                        "Blue Max                                   ",
                        "Bookchase                                  ",
                        "Brain Chain                                ",
                        "Brainstorm                                 ",
                        "Break the Safe                             ",
                        "Buccaneer                                  ",
                        "Buckaroo                                   ",
                        "Bul                                        ",
                        "Camp Granada                               ",
                        "Can't Stop                                 ",
                        "Candy Land                                 ",
                        "Capitol                                    ",
                        "Carcassonne                                ",
                        "Careers                                    ",
                        "Caribbean                                  ",
                        "Carrom                                     ",
                        "Cartagena                                  ",
                        "Caylus                                     ",
                        "Chapayev                                   ",
                        "Checkers                                   ",
                        "Chess                                      ",
                        "Chicken Cha Cha Cha                        ",
                        "CirKis                                     ",
                        "Civilization                               ",
                        "Clans                                      ",
                        "Clue                                       ",
                        "Cluedo                                     ",
                        "Cluedo (Clue in North America)             ",
                        "Conspiracy                                 ",
                        "Coppit                                     ",
                        "Cosmic Encounter                           ",
                        "Cranium                                    ",
                        "Crash! The bankrupt game                   ",
                        "Crokinole                                  ",
                        "Crosstrack                                 ",
                        "Da Vinci Game, The                         ",
                        "Daldos                                     ",
                        "Dark Tower                                 ",
                        "Dart Wars                                  ",
                        "Diamant                                    ",
                        "Die Macher                                 ",
                        "Diplomacy                                  ",
                        "Dixit                                      ",
                        "Djambi                                     ",
                        "Domaine                                    ",
                        "Dominion                                   ",
                        "Don't Break the Ice                        ",
                        "Don't Miss The Boat                        ",
                        "Don't Quote Me                             ",
                        "Don't Wake Daddy                           ",
                        "Doom: The Boardgame                        ",
                        "Dorn                                       ",
                        "Downfall                                   ",
                        "Drunter und Druber                         ",
                        "Dune                                       ",
                        "Dungeons and Dragons                       ",
                        "DVONN                                      ",
                        "El Grande                                  ",
                        "Elfenland                                  ",
                        "Empire Builder series                      ",
                        "Enchanted Forest                           ",
                        "English draughts                           ",
                        "Entdecker                                  ",
                        "Escape from Atlantis                       ",
                        "Evo                                        ",
                        "Fanorona                                   ",
                        "Farlander                                  ",
                        "Figure It Out                              ",
                        "Finance                                    ",
                        "Fireball Island                            ",
                        "Focus                                      ",
                        "Forbidden Bridge                           ",
                        "Formula De                                 ",
                        "Game of the Goose                          ",
                        "Ghettopoly                                 ",
                        "Ghosts                                     ",
                        "GiftTRAP                                   ",
                        "Giganten                                   ",
                        "Gipf                                       ",
                        "Girl Talk                                  ",
                        "Gnip Gnop                                  ",
                        "Go                                         ",
                        "Great Train Robbery                        ",
                        "GridIron Master                            ",
                        "Guess Who?                                 ",
                        "Hare and Hounds                            ",
                        "Hare and Tortoise                          ",
                        "Heroscape                                  ",
                        "Hex                                        ",
                        "Hey Pa! There's a Goat on the Roof         ",
                        "Hey, That's My Fish!                       ",
                        "Hi Ho! Cherry-O                            ",
                        "Hijara                                     ",
                        "History of the World                       ",
                        "Hotels                                     ",
                        "Hungry Hungry Hippos                       ",
                        "I'm the Boss!                              ",
                        "Imperial                                   ",
                        "Ingenious                                  ",
                        "Inkan aarre                                ",
                        "Isola                                      ",
                        "Janggi (Korean Chess)                      ",
                        "Java                                       ",
                        "Jenga                                      ",
                        "Journey through Europe                     ",
                        "Junta                                      ",
                        "Kalah                                      ",
                        "Kamisado                                   ",
                        "Kerplunk                                   ",
                        "Khet                                       ",
                        "Kill Doctor Lucky                          ",
                        "King Oil                                   ",
                        "Kingdoms                                   ",
                        "Kobenhavn                                  ",
                        "Kolejka                                    ",
                        "Krazy Maze                                 ",
                        "Landslide                                  ",
                        "Le Havre                                   ",
                        "Life                                       ",
                        "Liu po                                     ",
                        "Logo Board Game                            ",
                        "Lost Cities                                ",
                        "Lowenherz                                  ",
                        "Luck of the Draw                           ",
                        "Ludo                                       ",
                        "Mad Gab                                    ",
                        "Magic                                      ",
                        "MagnetX                                    ",
                        "Mall Madness                               ",
                        "Mancala                                    ",
                        "Manhattan                                  ",
                        "Master Labyrinth                           ",
                        "Master Mind                                ",
                        "Masterpiece                                ",
                        "Medici                                     ",
                        "Medina                                     ",
                        "Mensch argere dich nicht                   ",
                        "Merchant of Venus                          ",
                        "Mexica                                     ",
                        "Mine a million                             ",
                        "Mississippi Queen                          ",
                        "Modern Art                                 ",
                        "Monopoly                                   ",
                        "Monopoly Junior                            ",
                        "Mouse Trap                                 ",
                        "Niagara                                    ",
                        "Nine Men's Morris                          ",
                        "Obsession                                  ",
                        "Okey                                       ",
                        "Omega Virus                                ",
                        "Operation                                  ",
                        "Othello                                    ",
                        "Outrage!                                   ",
                        "Pack & Stack                               ",
                        "Pandemic                                   ",
                        "Parcheesi                                  ",
                        "Parques                                    ",
                        "Patolli                                    ",
                        "Pawn duel                                  ",
                        "Pay Day                                    ",
                        "Perfection                                 ",
                        "Personal Preference                        ",
                        "Pictionary                                 ",
                        "Pirate's Cove                              ",
                        "Plateau                                    ",
                        "Polarity                                   ",
                        "Poleconomy                                 ",
                        "Power Grid                                 ",
                        "Primordial Soup                            ",
                        "Princes of Florence                        ",
                        "Puerto Rico                                ",
                        "PUNCT                                      ",
                        "Quoridor                                   ",
                        "Qwirkle                                    ",
                        "Ra                                         ",
                        "Rail Baron                                 ",
                        "Rappakalja                                 ",
                        "Razzia                                     ",
                        "Richard Scarry Busy Town                   ",
                        "Ricochet Robots                            ",
                        "Risk                                       ",
                        "Risk 2210 AD                               ",
                        "Rithmomachy                                ",
                        "Rivers, Roads & Rails                      ",
                        "RoboRally                                  ",
                        "Rummikub                                   ",
                        "Rummoli                                    ",
                        "Sahkku                                     ",
                        "Saint Petersburg                           ",
                        "Samurai                                    ",
                        "San Marco                                  ",
                        "Scattergories                              ",
                        "Scotland Yard                              ",
                        "Scrabble                                   ",
                        "Senet                                      ",
                        "Sequence                                   ",
                        "Sequence Game                              ",
                        "Shadow Hunters                             ",
                        "Shadows over Camelot                       ",
                        "Sherlock Holmes Consulting Detective       ",
                        "Shogun/Samurai Swords                      ",
                        "Skirrid                                    ",
                        "Small World                                ",
                        "Snakes and Ladders                         ",
                        "Solarquest                                 ",
                        "Sorry!                                     ",
                        "Space Hop                                  ",
                        "Space Hulk                                 ",
                        "Spot It                                    ",
                        "Spy Alley                                  ",
                        "Squatter                                   ",
                        "Star Wars Epic Duels                       ",
                        "Star Wars Tactics                          ",
                        "Stock Ticker                               ",
                        "Strange Synergy                            ",
                        "Stratego                                   ",
                        "Subbuteo                                   ",
                        "Sugoroku                                   ",
                        "Summit                                     ",
                        "Super Quiz                                 ",
                        "Tâb                                        ",
                        "Tablut                                     ",
                        "Taj Mahal                                  ",
                        "Take It Easy                               ",
                        "Take Off!                                  ",
                        "Tantrix                                    ",
                        "TEG                                        ",
                        "The Cross and Circle                       ",
                        "The Game of Life                           ",
                        "The Great Train Robbery Board Game         ",
                        "The London Game                            ",
                        "The Really Nasty Horse Racing Game         ",
                        "The Settlers of Catan                      ",
                        "Through the Desert                         ",
                        "Thurn and Taxis                            ",
                        "Ticket to Ride                             ",
                        "Tigris & Euphrates                         ",
                        "Tikal                                      ",
                        "Timberland                                 ",
                        "Titan                                      ",
                        "Top Secret Spies                           ",
                        "Torres                                     ",
                        "Totopoly                                   ",
                        "Tracks to Telluride                        ",
                        "TransAmerica                               ",
                        "Transformers                               ",
                        "Trivial Pursuit                            ",
                        "Trouble                                    ",
                        "Tsuro                                      ",
                        "Twilight Imperium                          ",
                        "Twister                                    ",
                        "Ubongo                                     ",
                        "Vanished Planet                            ",
                        "Villa Paletti                              ",
                        "Vinci                                      ",
                        "War on Terror                              ",
                        "Wari                                       ",
                        "Yahtzee                                    ",
                        "YINSH                                      ",
                        "Yut                                        ",
                        "ZERTZ                                      ",
                        "Zombies!!!                                 "
                    });

                addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

                // Adding flow rules
                option = questions.get("activities").findOptionByText("Board or Card games");
                FlowRuleServices.insert(addedQuestion.getNetworkId(), option.getQuestionRef(), option.getRef(), addedQuestion.getRef());


                // Adding question to list
                questions.put("board-games", addedQuestion);
            }

            {
               // Adding question
               addedQuestionRef = QuestionServices.insert(userId, networkId, "What kind of dancing do you prefer to dance to?", 0, 10, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, true);

               // Adding options
               addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
               QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                   {
                       "Ballroom Dancing   ",
                       "Belly Dancing      ",
                       "Bhangra            ",
                       "Break Dance        ",
                       "Hip Hop dancing    ",
                       "Irish Dance        ",
                       "Robot dance        ",
                       "Salsa              ",
                       "Tap dancing        ",
                   });

               addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

               // Adding flow rules
               option = questions.get("activities").findOptionByText("Dancing");
               FlowRuleServices.insert(addedQuestion.getNetworkId(), option.getQuestionRef(), option.getRef(), addedQuestion.getRef());


               // Adding question to list
               questions.put("dancing", addedQuestion);
           }

           {
               // Adding question
               addedQuestionRef = QuestionServices.insert(userId, networkId, "Which instruments do you play?", 0, 5, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, true);

               // Adding options
               addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
               QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                   {
                       "Bass Guitar",
                       "Cello       ",
                       "Clarinet   ",
                       "Drums       ",
                       "Flute      ",
                       "French horn ",
                       "Guitar     ",
                       "Harp        ",
                       "Oboe        ",
                       "Piano      ",
                       "Saxophone   ",
                       "Trumpet     ",
                       "Violin     ",
                       "Xylophone   ",
                   });

               addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

               // Adding flow rules
               option = questions.get("activities").findOptionByText("Playing music");
               FlowRuleServices.insert(addedQuestion.getNetworkId(), option.getQuestionRef(), option.getRef(), addedQuestion.getRef());


               // Adding question to list
               questions.put("instruments", addedQuestion);
           }

        }



        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "Currently, what day of the week are you usually free?", 0, 5, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                {
                    "Mondays",
                    "Tuesdays",
                    "Wednesdays",
                    "Thursdays",
                    "Fridays",
                    "Saturdays",
                    "Sundays",
                });

            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), QuestionDao.ROOT_QUESTION_REF, QuestionOptionDao.ANY_OPTION_REF, addedQuestion.getRef());


            // Adding question to list
            questions.put("free", addedQuestion);
        }

        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "What languages do you speak?", 0, 5, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                {
                    "Acehnese                                     ",
                    "Afrikaans                                    ",
                    "Akan (Twi, Fante)                            ",
                    "Albanian                                     ",
                    "Amharic                                      ",
                    "Arabic                                       ",
                    "Armenian                                     ",
                    "Assamese                                     ",
                    "Awadhi                                       ",
                    "Azerbaijani                                  ",
                    "Bagheli                                      ",
                    "Balinese                                     ",
                    "Balochi                                      ",
                    "Bambara (Malinke, Jula)                      ",
                    "Batak                                        ",
                    "Bavarian                                     ",
                    "Belarusian                                   ",
                    "Bemba                                        ",
                    "Bengali (Bangla)                             ",
                    "Bhili (Wagdi, etc.)                          ",
                    "Bhojpuri                                     ",
                    "Bikol                                        ",
                    "Buginese                                     ",
                    "Bulgarian                                    ",
                    "Burmese                                      ",
                    "Catalan (Valencian)                          ",
                    "Cebuano                                      ",
                    "Chewa (Nyanja)                               ",
                    "Chhattisgarhi                                ",
                    "Chittagonian                                 ",
                    "Czech                                        ",
                    "Danish                                       ",
                    "Deccan                                       ",
                    "Dholuo (Luo proper)                          ",
                    "Dogri (Kangri)                               ",
                    "Dutch                                        ",
                    "Efik (Ibibio–Efik)                           ",
                    "English                                      ",
                    "Ewe                                          ",
                    "Farsi                                        ",
                    "Finnish                                      ",
                    "French                                       ",
                    "Fula (Fulani, Fulfulde, Pulaar)              ",
                    "Galician                                     ",
                    "Gan                                          ",
                    "Ganda (Luganda)                              ",
                    "Georgian                                     ",
                    "German                                       ",
                    "Gikuyu                                       ",
                    "Greek                                        ",
                    "Guarani                                      ",
                    "Gujarati                                     ",
                    "Haitian Creole                               ",
                    "Hakka                                        ",
                    "Haryanvi                                     ",
                    "Hausa                                        ",
                    "Hebrew                                       ",
                    "Hiligaynon                                   ",
                    "Hindi-Urdu (Hindustani)                      ",
                    "Hungarian                                    ",
                    "Igbo                                         ",
                    "Ilokano                                      ",
                    "Italian                                      ",
                    "Jamaican Creole                              ",
                    "Japanese                                     ",
                    "Javanese                                     ",
                    "Kamba                                        ",
                    "Kanauji                                      ",
                    "Kannada                                      ",
                    "Kanuri (Kanembu)                             ",
                    "Kashmiri                                     ",
                    "Kazakh                                       ",
                    "Khmer                                        ",
                    "Kimbundu (North Mbundu)                      ",
                    "Kituba                                       ",
                    "Kongo                                        ",
                    "Konkani                                      ",
                    "Konkani                                      ",
                    "Korean                                       ",
                    "Kurdish                                      ",
                    "Kyrgyz                                       ",
                    "Lao–Isan                                     ",
                    "Lithuanian                                   ",
                    "Lombard                                      ",
                    "Luyia                                        ",
                    "Madurese                                     ",
                    "Magahi                                       ",
                    "Maithili                                     ",
                    "Makuwa (Lomwe)                               ",
                    "Malagasy                                     ",
                    "Malay (Malaysian-Indonesian)                 ",
                    "Malayalam                                    ",
                    "Mandarin                                     ",
                    "Mandingo (Maninka)                           ",
                    "Marathi                                      ",
                    "Marwari                                      ",
                    "Mazanderani–Gilaki                           ",
                    "Min Bei                                      ",
                    "Min Dong (Fuzhou)                            ",
                    "Min Nan (Amoy, Hokkien,Taiwanese)            ",
                    "Minangkabau                                  ",
                    "Mongolian                                    ",
                    "Mossi-Dagomba                                ",
                    "Neapolitan (Calabrese)                       ",
                    "Nepali                                       ",
                    "Northern Berber                              ",
                    "Norwegian                                    ",
                    "Oriya                                        ",
                    "Oromo                                        ",
                    "Pashto                                       ",
                    "Piemonteis                                   ",
                    "Polish                                       ",
                    "Portuguese                                   ",
                    "Punjabi                                      ",
                    "Rajasthani                                   ",
                    "Rangpuri                                     ",
                    "Romanian                                     ",
                    "Russian                                      ",
                    "Rwanda-Rundi                                 ",
                    "Santali                                      ",
                    "Serbo-Croatian (Bosnian, Croatian, Serbian)  ",
                    "Shan                                         ",
                    "Shan                                         ",
                    "Shona                                        ",
                    "Sicilian                                     ",
                    "Sindhi                                       ",
                    "Sinhalese                                    ",
                    "Slovak                                       ",
                    "Somali                                       ",
                    "Sotho–Tswana                                 ",
                    "Southern Quechua                             ",
                    "Southern Thai                                ",
                    "Spanish (Castilian)                          ",
                    "Sukuma-Nyamwezi                              ",
                    "Sundanese                                    ",
                    "Swedish                                      ",
                    "Sylheti                                      ",
                    "Tagalog (Filipino)                           ",
                    "Tamil                                        ",
                    "Tatar-Bashkir                                ",
                    "Telugu                                       ",
                    "Thai                                         ",
                    "Tigrinya                                     ",
                    "Tshiluba (Luba-Kasai)                        ",
                    "Tsonga                                       ",
                    "Turkish                                      ",
                    "Turkmen                                      ",
                    "Ukrainian                                    ",
                    "Umbundu (South Mbundu)                       ",
                    "Uyghur                                       ",
                    "Uzbek                                        ",
                    "Venetian                                     ",
                    "Vietnamese                                   ",
                    "Wolof                                        ",
                    "Wu (Shanghainese)                            ",
                    "Xhosa                                        ",
                    "Xiang (Hunanese)                             ",
                    "Yoruba                                       ",
                    "Yue (Cantonese)                              ",
                    "Zulu                                         "
                });

            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), QuestionDao.ROOT_QUESTION_REF, QuestionOptionDao.ANY_OPTION_REF, addedQuestion.getRef());


            // Adding question to list
            questions.put("language", addedQuestion);
        }

        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "Do you have any children?", 0, 1, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                {
                    "None",
                    "1",
                    "2",
                    "3",
                    "4",
                    "More than 4"
                });

            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), QuestionDao.ROOT_QUESTION_REF, QuestionOptionDao.ANY_OPTION_REF, addedQuestion.getRef());

            // Adding question to list
            questions.put("children", addedQuestion);
        }


    }
}
