package com.questy.admin;

import com.questy.dao.QuestionDao;
import com.questy.domain.Question;
import com.questy.domain.QuestionOption;
import com.questy.enums.AnswerVisibilityEnum;
import com.questy.services.FlowRuleServices;
import com.questy.services.QuestionOptionServices;
import com.questy.services.QuestionServices;

import java.util.HashMap;
import java.util.Map;

public class Health {

    public static void create(Integer networkId) throws Exception {

        Integer userId = 2;

        Integer addedQuestionRef = null;
        Question addedQuestion = null;
        QuestionOption option = null;
        Map<String, Question> questions = new HashMap<String, Question>();

        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "What dietary preferences(s) best describes you?", 0, 3, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                    {
                            "Carnivore",
                            "Pescetarian",
                            "Vegetarian",
                            "Vegan",
                            "Gluten Free",
                            "Lactose Free",
                            "Raw"
                    });
            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), Question.ROOT_QUESTION_REF, QuestionOption.ANY_OPTION_REF, addedQuestion.getRef());


            // Adding question to list
            questions.put("diet", addedQuestion);
        }


        // Add question with options and flow rule
        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "How tall are you?", 0, 1, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                    {
                            "4 ft 0 in",
                            "4 ft 0.5 in",
                            "4 ft 1 in",
                            "4 ft 1.5 in",
                            "4 ft 2 in",
                            "4 ft 2.5 in",
                            "4 ft 3 in",
                            "4 ft 3.5 in",
                            "4 ft 4 in",
                            "4 ft 4.5 in",
                            "4 ft 5 in",
                            "4 ft 5.5 in",
                            "4 ft 6 in",
                            "4 ft 6.5 in",
                            "4 ft 7 in",
                            "4 ft 7.5 in",
                            "4 ft 8 in",
                            "4 ft 8.5 in",
                            "4 ft 9 in",
                            "4 ft 9.5 in",
                            "4 ft 10 in",
                            "4 ft 10.5 in",
                            "4 ft 11 in",
                            "4 ft 11.5 in",
                            "5 ft 0 in",
                            "5 ft 0.5 in",
                            "5 ft 1 in",
                            "5 ft 1.5 in",
                            "5 ft 2 in",
                            "5 ft 2.5 in",
                            "5 ft 3 in",
                            "5 ft 3.5 in",
                            "5 ft 4 in",
                            "5 ft 4.5 in",
                            "5 ft 5 in",
                            "5 ft 5.5 in",
                            "5 ft 6 in",
                            "5 ft 6.5 in",
                            "5 ft 7 in",
                            "5 ft 7.5 in",
                            "5 ft 8 in",
                            "5 ft 8.5 in",
                            "5 ft 9 in",
                            "5 ft 9.5 in",
                            "5 ft 10 in",
                            "5 ft 10.5 in",
                            "5 ft 11 in",
                            "5 ft 11.5 in",
                            "6 ft 0 in",
                            "6 ft 0.5 in",
                            "6 ft 1 in",
                            "6 ft 1.5 in",
                            "6 ft 2 in",
                            "6 ft 2.5 in",
                            "6 ft 3 in",
                            "6 ft 3.5 in",
                            "6 ft 4 in",
                            "6 ft 4.5 in",
                            "6 ft 5 in",
                            "6 ft 5.5 in",
                            "6 ft 6 in",
                            "6 ft 6.5 in",
                            "6 ft 7 in",
                            "6 ft 7.5 in",
                            "6 ft 8 in",
                            "6 ft 8.5 in",
                            "6 ft 9 in",
                            "6 ft 9.5 in",
                            "6 ft 10 in",
                            "6 ft 10.5 in",
                            "6 ft 11 in",
                            "6 ft 11.5 in",
                            "7 ft 0 in",
                            "7 ft 0.5 in",
                            "7 ft 1 in",
                            "7 ft 1.5 in",
                            "7 ft 2 in",
                            "7 ft 2.5 in",
                            "7 ft 3 in",
                            "7 ft 3.5 in",
                            "7 ft 4 in",
                            "7 ft 4.5 in",
                            "7 ft 5 in",
                            "7 ft 5.5 in",
                            "7 ft 6 in",
                            "7 ft 6.5 in",
                            "7 ft 7 in",
                            "7 ft 7.5 in",
                            "7 ft 8 in",
                            "7 ft 8.5 in",
                            "7 ft 9 in",
                            "7 ft 9.5 in",
                            "7 ft 10 in",
                            "7 ft 10.5 in",
                            "7 ft 11 in",
                            "7 ft 11.5 in",
                            "8 ft 0 in",
                            "8 ft 0.5 in",
                            "8 ft 1 in",
                            "8 ft 1.5 in",
                            "8 ft 2 in",
                            "8 ft 2.5 in",
                            "8 ft 3 in",
                            "8 ft 3.5 in",
                            "8 ft 4 in",
                            "8 ft 4.5 in",
                            "8 ft 5 in",
                            "8 ft 5.5 in",
                            "8 ft 6 in",
                            "8 ft 6.5 in",
                            "8 ft 7 in",
                            "8 ft 7.5 in",
                            "8 ft 8 in",
                            "8 ft 8.5 in",
                            "8 ft 9 in",
                            "8 ft 9.5 in",
                            "8 ft 10 in",
                            "8 ft 10.5 in",
                            "8 ft 11 in",
                            "8 ft 11.5 in",
                            "120 cm",
                            "121 cm",
                            "122 cm",
                            "123 cm",
                            "124 cm",
                            "125 cm",
                            "126 cm",
                            "127 cm",
                            "128 cm",
                            "129 cm",
                            "130 cm",
                            "131 cm",
                            "132 cm",
                            "133 cm",
                            "134 cm",
                            "135 cm",
                            "136 cm",
                            "137 cm",
                            "138 cm",
                            "139 cm",
                            "140 cm",
                            "141 cm",
                            "142 cm",
                            "143 cm",
                            "144 cm",
                            "145 cm",
                            "146 cm",
                            "147 cm",
                            "148 cm",
                            "149 cm",
                            "150 cm",
                            "151 cm",
                            "152 cm",
                            "153 cm",
                            "154 cm",
                            "155 cm",
                            "156 cm",
                            "157 cm",
                            "158 cm",
                            "159 cm",
                            "160 cm",
                            "161 cm",
                            "162 cm",
                            "163 cm",
                            "164 cm",
                            "165 cm",
                            "166 cm",
                            "167 cm",
                            "168 cm",
                            "169 cm",
                            "170 cm",
                            "171 cm",
                            "172 cm",
                            "173 cm",
                            "174 cm",
                            "175 cm",
                            "176 cm",
                            "177 cm",
                            "178 cm",
                            "179 cm",
                            "180 cm",
                            "181 cm",
                            "182 cm",
                            "183 cm",
                            "184 cm",
                            "185 cm",
                            "186 cm",
                            "187 cm",
                            "188 cm",
                            "189 cm",
                            "190 cm",
                            "191 cm",
                            "192 cm",
                            "193 cm",
                            "194 cm",
                            "195 cm",
                            "196 cm",
                            "197 cm",
                            "198 cm",
                            "199 cm",
                            "200 cm",
                            "201 cm",
                            "202 cm",
                            "203 cm",
                            "204 cm",
                            "205 cm",
                            "206 cm",
                            "207 cm",
                            "208 cm",
                            "209 cm",
                            "210 cm",
                            "211 cm",
                            "212 cm",
                            "213 cm",
                            "214 cm",
                            "215 cm",
                            "216 cm",
                            "217 cm",
                            "218 cm",
                            "219 cm",
                            "220 cm",
                            "221 cm",
                            "222 cm",
                            "223 cm",
                            "224 cm",
                            "225 cm",
                            "226 cm",
                            "227 cm",
                            "228 cm",
                            "229 cm",
                            "230 cm",
                            "231 cm",
                            "232 cm",
                            "233 cm",
                            "234 cm",
                            "235 cm",
                            "236 cm",
                            "237 cm",
                            "238 cm",
                            "239 cm",
                            "240 cm",
                            "241 cm",
                            "242 cm",
                            "243 cm",
                            "244 cm",
                            "245 cm",
                            "246 cm",
                            "247 cm",
                            "248 cm",
                            "249 cm"
                    });
            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), Question.ROOT_QUESTION_REF, QuestionOption.ANY_OPTION_REF, addedQuestion.getRef());


            // Adding question to list
            questions.put("tall", addedQuestion);
        }

        // Add question with options and flow rule
        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "What is your current shoe size?", 0, 1, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                    {
                            "US - 1",
                            "US - 1.5",
                            "US - 2",
                            "US - 2.5",
                            "US - 3",
                            "US - 3.5",
                            "US - 4",
                            "US - 4.5",
                            "US - 5",
                            "US - 5.5",
                            "US - 6",
                            "US - 6.5",
                            "US - 7",
                            "US - 7.5",
                            "US - 8",
                            "US - 8.5",
                            "US - 9",
                            "US - 9.5",
                            "US - 10",
                            "US - 10.5",
                            "US - 11",
                            "US - 11.5",
                            "US - 12",
                            "US - 12.5",
                            "US - 13",
                            "US - 13.5",
                            "US - 14",
                            "US - 14.5",
                            "US - 15",
                            "US - 15.5",
                            "US - 16",
                            "US - 16.5",
                            "US - 17",
                            "UK - 1",
                            "UK - 1.5",
                            "UK - 2",
                            "UK - 2.5",
                            "UK - 3",
                            "UK - 3.5",
                            "UK - 4",
                            "UK - 4.5",
                            "UK - 5",
                            "UK - 5.5",
                            "UK - 6",
                            "UK - 6.5",
                            "UK - 7",
                            "UK - 7.5",
                            "UK - 8",
                            "UK - 8.5",
                            "UK - 9",
                            "UK - 9.5",
                            "UK - 10",
                            "UK - 10.5",
                            "UK - 11",
                            "UK - 11.5",
                            "UK - 12",
                            "UK - 12.5",
                            "UK - 13",
                            "UK - 13.5",
                            "UK - 14",
                            "UK - 14.5",
                            "UK - 15",
                            "UK - 15.5",
                            "UK - 16",
                            "UK - 16.5",
                            "UK - 17",
                            "EU - 31",
                            "EU - 31.5",
                            "EU - 32",
                            "EU - 32.5",
                            "EU - 33",
                            "EU - 33.5",
                            "EU - 34",
                            "EU - 34.5",
                            "EU - 35",
                            "EU - 35.5",
                            "EU - 36",
                            "EU - 36.5",
                            "EU - 37",
                            "EU - 37.5",
                            "EU - 38",
                            "EU - 38.5",
                            "EU - 39",
                            "EU - 39.5",
                            "EU - 40",
                            "EU - 40.5",
                            "EU - 41",
                            "EU - 41.5",
                            "EU - 42",
                            "EU - 42.5",
                            "EU - 43",
                            "EU - 43.5",
                            "EU - 44",
                            "EU - 44.5",
                            "EU - 45",
                            "EU - 45.5",
                            "EU - 46",
                            "EU - 46.5",
                            "EU - 47",
                            "China - 32",
                            "China - 32.5",
                            "China - 33",
                            "China - 33.5",
                            "China - 34",
                            "China - 34.5",
                            "China - 35",
                            "China - 35.5",
                            "China - 36",
                            "China - 36.5",
                            "China - 37",
                            "China - 37.5",
                            "China - 38",
                            "China - 38.5",
                            "China - 39",
                            "China - 39.5",
                            "China - 40",
                            "China - 40.5",
                            "China - 41",
                            "China - 41.5",
                            "China - 42",
                            "China - 42.5",
                            "China - 43",
                            "China - 43.5",
                            "China - 44",
                            "China - 44.5",
                            "China - 45",
                            "China - 45.5",
                            "China - 46",
                            "China - 46.5",
                            "China - 47",
                            "China - 47.5",
                            "China - 48",
                            "China - 48.5",
                            "China - 49",
                            "China - 49.5",
                            "China - 50",
                            "China - 50.5",


                    });
            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), Question.ROOT_QUESTION_REF, QuestionOption.ANY_OPTION_REF, addedQuestion.getRef());


            // Adding question to list
            questions.put("shoe", addedQuestion);
        }

        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "In the last 6 months, how often have you exercised?", 0, 1, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                    {
                            "I haven't exercised",
                            "Every three months",
                            "Every two months",
                            "Every month",
                            "Every 3 weeks",
                            "Every 2 weeks",
                            "Every week",
                            "Every 5 days",
                            "Every 3 days",
                            "Every 2 days",
                            "Every day",
                            "More than once a day"
                    });
            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), Question.ROOT_QUESTION_REF, QuestionOption.ANY_OPTION_REF, addedQuestion.getRef());


            // Adding question to list
            questions.put("exercise", addedQuestion);
        }

        {
            // Adding question
            addedQuestionRef = QuestionServices.insert(userId, networkId, "How much do you weight?", 0, 1, AnswerVisibilityEnum.PUBLIC, AnswerVisibilityEnum.PROTECTED, false);

            // Adding options
            addedQuestion = QuestionDao.getByNetworkIdAndRef(null, networkId, addedQuestionRef);
            QuestionOptionServices.addOptions(addedQuestion.getNetworkId(), addedQuestion.getRef(), userId, new String[]
                    {
                            "under 100 lbs",
                            "100 lbs",
                            "100.5 lbs",
                            "101 lbs",
                            "101.5 lbs",
                            "102 lbs",
                            "102.5 lbs",
                            "103 lbs",
                            "103.5 lbs",
                            "104 lbs",
                            "104.5 lbs",
                            "105 lbs",
                            "105.5 lbs",
                            "106 lbs",
                            "106.5 lbs",
                            "107 lbs",
                            "107.5 lbs",
                            "108 lbs",
                            "108.5 lbs",
                            "109 lbs",
                            "109.5 lbs",
                            "110 lbs",
                            "110.5 lbs",
                            "111 lbs",
                            "111.5 lbs",
                            "112 lbs",
                            "112.5 lbs",
                            "113 lbs",
                            "113.5 lbs",
                            "114 lbs",
                            "114.5 lbs",
                            "115 lbs",
                            "115.5 lbs",
                            "116 lbs",
                            "116.5 lbs",
                            "117 lbs",
                            "117.5 lbs",
                            "118 lbs",
                            "118.5 lbs",
                            "119 lbs",
                            "119.5 lbs",
                            "120 lbs",
                            "120.5 lbs",
                            "121 lbs",
                            "121.5 lbs",
                            "122 lbs",
                            "122.5 lbs",
                            "123 lbs",
                            "123.5 lbs",
                            "124 lbs",
                            "124.5 lbs",
                            "125 lbs",
                            "125.5 lbs",
                            "126 lbs",
                            "126.5 lbs",
                            "127 lbs",
                            "127.5 lbs",
                            "128 lbs",
                            "128.5 lbs",
                            "129 lbs",
                            "129.5 lbs",
                            "120 lbs",
                            "120.5 lbs",
                            "131 lbs",
                            "131.5 lbs",
                            "132 lbs",
                            "132.5 lbs",
                            "133 lbs",
                            "133.5 lbs",
                            "134 lbs",
                            "134.5 lbs",
                            "135 lbs",
                            "135.5 lbs",
                            "136 lbs",
                            "136.5 lbs",
                            "137 lbs",
                            "137.5 lbs",
                            "138 lbs",
                            "138.5 lbs",
                            "139 lbs",
                            "139.5 lbs",
                            "140 lbs",
                            "140.5 lbs",
                            "141 lbs",
                            "141.5 lbs",
                            "142 lbs",
                            "142.5 lbs",
                            "143 lbs",
                            "143.5 lbs",
                            "144 lbs",
                            "144.5 lbs",
                            "145 lbs",
                            "145.5 lbs",
                            "146 lbs",
                            "146.5 lbs",
                            "147 lbs",
                            "147.5 lbs",
                            "148 lbs",
                            "148.5 lbs",
                            "149 lbs",
                            "149.5 lbs",
                            "150 lbs",
                            "150.5 lbs",
                            "151 lbs",
                            "151.5 lbs",
                            "152 lbs",
                            "152.5 lbs",
                            "153 lbs",
                            "153.5 lbs",
                            "154 lbs",
                            "154.5 lbs",
                            "155 lbs",
                            "155.5 lbs",
                            "156 lbs",
                            "156.5 lbs",
                            "157 lbs",
                            "157.5 lbs",
                            "158 lbs",
                            "158.5 lbs",
                            "159 lbs",
                            "159.5 lbs",
                            "160 lbs",
                            "160.5 lbs",
                            "161 lbs",
                            "161.5 lbs",
                            "162 lbs",
                            "162.5 lbs",
                            "163 lbs",
                            "163.5 lbs",
                            "164 lbs",
                            "164.5 lbs",
                            "165 lbs",
                            "165.5 lbs",
                            "166 lbs",
                            "166.5 lbs",
                            "167 lbs",
                            "167.5 lbs",
                            "168 lbs",
                            "168.5 lbs",
                            "169 lbs",
                            "169.5 lbs",
                            "170 lbs",
                            "170.5 lbs",
                            "171 lbs",
                            "171.5 lbs",
                            "172 lbs",
                            "172.5 lbs",
                            "173 lbs",
                            "173.5 lbs",
                            "174 lbs",
                            "174.5 lbs",
                            "175 lbs",
                            "175.5 lbs",
                            "176 lbs",
                            "176.5 lbs",
                            "177 lbs",
                            "177.5 lbs",
                            "178 lbs",
                            "178.5 lbs",
                            "179 lbs",
                            "179.5 lbs",
                            "180 lbs",
                            "180.5 lbs",
                            "181 lbs",
                            "181.5 lbs",
                            "182 lbs",
                            "182.5 lbs",
                            "183 lbs",
                            "183.5 lbs",
                            "184 lbs",
                            "184.5 lbs",
                            "185 lbs",
                            "185.5 lbs",
                            "186 lbs",
                            "186.5 lbs",
                            "187 lbs",
                            "187.5 lbs",
                            "188 lbs",
                            "188.5 lbs",
                            "189 lbs",
                            "189.5 lbs",
                            "190 lbs",
                            "190.5 lbs",
                            "191 lbs",
                            "191.5 lbs",
                            "192 lbs",
                            "192.5 lbs",
                            "193 lbs",
                            "193.5 lbs",
                            "194 lbs",
                            "194.5 lbs",
                            "195 lbs",
                            "195.5 lbs",
                            "196 lbs",
                            "196.5 lbs",
                            "197 lbs",
                            "197.5 lbs",
                            "198 lbs",
                            "198.5 lbs",
                            "199 lbs",
                            "199.5 lbs",
                            "200 lbs",
                            "200.5 lbs",
                            "201 lbs",
                            "201.5 lbs",
                            "202 lbs",
                            "202.5 lbs",
                            "203 lbs",
                            "203.5 lbs",
                            "204 lbs",
                            "204.5 lbs",
                            "205 lbs",
                            "205.5 lbs",
                            "206 lbs",
                            "206.5 lbs",
                            "207 lbs",
                            "207.5 lbs",
                            "208 lbs",
                            "208.5 lbs",
                            "209 lbs",
                            "209.5 lbs",
                            "210 lbs",
                            "210.5 lbs",
                            "211 lbs",
                            "211.5 lbs",
                            "212 lbs",
                            "212.5 lbs",
                            "213 lbs",
                            "213.5 lbs",
                            "214 lbs",
                            "214.5 lbs",
                            "215 lbs",
                            "215.5 lbs",
                            "216 lbs",
                            "216.5 lbs",
                            "217 lbs",
                            "217.5 lbs",
                            "218 lbs",
                            "218.5 lbs",
                            "219 lbs",
                            "219.5 lbs",
                            "220.5 lbs",
                            "221 lbs",
                            "221.5 lbs",
                            "222 lbs",
                            "222.5 lbs",
                            "223 lbs",
                            "223.5 lbs",
                            "224 lbs",
                            "224.5 lbs",
                            "225 lbs",
                            "225.5 lbs",
                            "226 lbs",
                            "226.5 lbs",
                            "227 lbs",
                            "227.5 lbs",
                            "228 lbs",
                            "228.5 lbs",
                            "229 lbs",
                            "229.5 lbs",
                            "230.5 lbs",
                            "231 lbs",
                            "231.5 lbs",
                            "232 lbs",
                            "232.5 lbs",
                            "233 lbs",
                            "233.5 lbs",
                            "234 lbs",
                            "234.5 lbs",
                            "235 lbs",
                            "235.5 lbs",
                            "236 lbs",
                            "236.5 lbs",
                            "237 lbs",
                            "237.5 lbs",
                            "238 lbs",
                            "238.5 lbs",
                            "239 lbs",
                            "239.5 lbs",
                            "over 240 lbs",
                            "under 45 kg",
                            "45 kg",
                            "45.5 kg",
                            "46 ",
                            "46.5 kg",
                            "47 kg",
                            "47.5 kg",
                            "48 kg",
                            "48.5 kg",
                            "49 kg",
                            "49.5 kg",
                            "50 kg",
                            "51.5 kg",
                            "52 kg",
                            "52.5 kg",
                            "53 kg",
                            "53.5 kg",
                            "54 kg",
                            "54.5 kg",
                            "55 kg",
                            "55.5 kg",
                            "56 kg",
                            "56.5 kg",
                            "57 kg",
                            "57.5 kg",
                            "58 kg",
                            "58.5 kg",
                            "59 kg",
                            "59.5 kg",
                            "60 kg",
                            "60.5 kg",
                            "61 kg",
                            "61.5 kg",
                            "62 kg",
                            "62.5 kg",
                            "63 kg",
                            "63.5 kg",
                            "64 kg",
                            "64.5 kg",
                            "65 kg",
                            "65.5 kg",
                            "66 kg",
                            "66.5 kg",
                            "67 kg",
                            "67.5 kg",
                            "68 kg",
                            "68.5 kg",
                            "69 kg",
                            "69.5 kg",
                            "70 kg",
                            "70.5 kg",
                            "71 kg",
                            "71.5 kg",
                            "72 kg",
                            "72.5 kg",
                            "73 kg",
                            "73.5 kg",
                            "74 kg",
                            "74.5 kg",
                            "75 kg",
                            "75.5 kg",
                            "76 kg",
                            "76.5 kg",
                            "77 kg",
                            "77.5 kg",
                            "78 kg",
                            "78.5 kg",
                            "79 kg",
                            "79.5 kg",
                            "80 kg",
                            "80.5 kg",
                            "81 kg",
                            "81.5 kg",
                            "82 kg",
                            "82.5 kg",
                            "83 kg",
                            "83.5 kg",
                            "84 kg",
                            "84.5 kg",
                            "85 kg",
                            "85.5 kg",
                            "86 kg",
                            "86.5 kg",
                            "87 kg",
                            "87.5 kg",
                            "88 kg",
                            "88.5 kg",
                            "89 kg",
                            "89.5 kg",
                            "90 kg",
                            "90.5 kg",
                            "91 kg",
                            "91.5 kg",
                            "92 kg",
                            "92.5 kg",
                            "93 kg",
                            "93.5 kg",
                            "94 kg",
                            "94.5 kg",
                            "95 kg",
                            "95.5 kg",
                            "96 kg",
                            "96.5 kg",
                            "97 kg",
                            "97.5 kg",
                            "98 kg",
                            "98.5 kg",
                            "99 kg",
                            "99.5 kg",
                            "100 kg",
                            "100.5 kg",
                            "101 kg",
                            "101.5 kg",
                            "102 kg",
                            "102.5 kg",
                            "103 kg",
                            "103.5 kg",
                            "104 kg",
                            "104.5 kg",
                            "105 kg",
                            "105.5 kg",
                            "106 kg",
                            "106.5 kg",
                            "107 kg",
                            "107.5 kg",
                            "108 kg",
                            "over 108 kg"
                    });
            addedQuestion = QuestionServices.getByNetworkIdAndRef(networkId, addedQuestion.getRef());

            // Adding flow rules
            FlowRuleServices.insert(addedQuestion.getNetworkId(), Question.ROOT_QUESTION_REF, QuestionOption.ANY_OPTION_REF, addedQuestion.getRef());

            // Adding question to list
            questions.put("weight", addedQuestion);
        }
    }
}
